spring:
  application:
    name: telegram-bot
    performance:
      threshold-ms: 500
    notifications:
      enabled: true
      chat-id: 1
      include-stacktrace: true
      stacktrace-max-lines: 15
      skip-exceptions:
        - com.example.telegram_bot.exception.AccessDeniedException

telegrambots:
  botToken: 8342502229:AAGjhx4-Zvtjyau5nMyKup5l6vzwoq_K82k
  admin-users: 1, 15, 5000, -112512412, 1234

logging:
  level:
    com.example.telegram_bot.aspect: DEBUG